### ISSUE TITLE
How to fix F vs C?

### ISSUE THREAD

**Issue by jlg89** [dotfortun3-code/homebridge-infinitude-schedules#1]
This plugin is a wonderful Christmas present! Thanks for the fork. :D

I've just installed the plugin, and it created HomeKit thermostats for all three zones and is pulling data, but the temps are off due to an F/C conversion issue somewhere.

Actual temps (from Infinitude http): Current (rt) 70, Heat (htsp) 69, Cool (clsp) 77
Plugin readings (in HomeKit): Current 158, Heat 77, Cool 95

So either HomeKit is assuming that it's getting Celsius from the plugin, or the plugin is assuming that it's getting Celsius from Infinitude. Where do I fix this?

**Comment by dotfortun3-code** [comment]
Glad you like it! You are correct, it is assuming C from the t-stat. I will take a look and either fix the calculation or add an F/C option in the config for it. I believe I can check whether the t-stat is using C vs F and that should fix it.

**Comment by dotfortun3-code** [comment]
I released a new version (0.5.1) that should fix this issue.

**Comment by jlg89** [comment]
That seems to have fixed it. Super work. I'll mess around with it, with a smile on my face, and let you know if I come up with anything else.
